language: node_js
node_js:
- 6.10.0
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- 1.9.4
- export PATH="$HOME/.yarn/bin:$PATH"
install:
- yarn && cd client && yarn && cd ..
before_script: ./scripts/build.sh
deploy:
  skip_cleanup: true
  provider: heroku
  app: virtual-coin-exchange
  api_key:
    secure: cyTMAwZTxyVV1ku/tnad1XNVBPjE4/XH04j16eYvPnSeeF2qiNwbB2rUfM4EXA4pgMlJN7dfciad5duB53VR5RkqTQoqIl6Ruo/tOP6D8Sf1tFBPKs0mpZwd1IVIesR2PVnmo81K8JERv+XjZXH1i5r30xV79NKN1n5r59LUUSYoxlLuvFFxTewWoyNzCXDZg31QqMGXv0tD0KhN4GZUoa6QeJ7aY8BdjlhGUXFAFfyyXowzN+4HbAc3YANZSFv/3M0Rv41X4S8HlGqj6Jn5rEZ7YaMNhhj3NdP47vClURv92i7jTkH9t7gQIrEJ1EDdpDdWAS0Fs7RpxEGHsMLCY6X3ti/eZHm5Vv+UR63Vd5Wm2MepLtSqMLt2/fHXEF+6LeRwJQ02TUYv+fyMslEngB3yxVdtbV+1p7oUQ3Vpd40RRHVkBGzWfRd7RpCPC+QIxqubYg0Xb/MFHD7q4+mMhHz3ZTNiVS2t4Pm0m+wXtuPM2xWEqLjCPQzDY7ZvtcXRObVWxB0VgCzn+Hv2G+MSTstOJxgmP++6uLvq66jeyNAgNIXu2HWaeE+Ipxo7B6CJpv/2S2JL+B89+awBfYGqUVBYveHMO9rGczzRotCaN07M4VnjDkOW24Jf0DLQ7wBxHNBvJo95tlvPmKs9wLgTks+HBIT7spZyolpaDfPiTCc=
